version: '3.8'

services:
  kafka:
    build:
      context: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  spark:
    build:
      context: ./spark
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  python-app:
    build:
      context: ./python-app
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - spark
    environment:
      KAFKA_HOST: kafka
      SPARK_MASTER: spark://spark:7077
  

  druid:
    image: apache/druid:26.0.0
    ports:
      - "8888:8888"
    environment:
      - DRUID_X=enable
    depends_on:
      - spark

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    depends_on:
      - druid


networks:
  default:
    driver: bridge